imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
         name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# LiipFunctionnalTest
liip_functional_test:
    cache_sqlite_db: true

# Doctrine ORM
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: '%kernel.project_dir%/var/data/dbinventorytest'
