user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

inventory:
    resource: "@InventoryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
