inventory_provider:
    resource: "@InventoryBundle/Controller/ProviderController.php"
    type:     annotation

inventory_client:
    resource: "@InventoryBundle/Controller/ClientController.php"
    type:     annotation

inventory_product:
    resource: "@InventoryBundle/Controller/ProductController.php"
    type:     annotation

inventory_category:
    resource: "@InventoryBundle/Controller/CategoryController.php"
    type:     annotation

inventory:
    resource: "@InventoryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
