<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotaleStockByProduct() {
        $query = $this->createQueryBuilder('q')
                        ->join('q.product','product')
                        ->select('SUM(q.stock) as stock,product.id')
                        ->groupBy('q.product')
                        ->getQuery();
        return $query->getScalarResult();
    }
}
