<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * OrderPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
