<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * OrderSaleProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSaleProductRepository extends \Doctrine\ORM\EntityRepository
{
}
