<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * OrderSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
