<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * OrderPurchaseProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderPurchaseProductRepository extends \Doctrine\ORM\EntityRepository
{
}
