<?php

namespace Tlc\InventoryBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function UpdateAmountProduit(array $total) {
        foreach ($total as $tot) {
            $this->setAmount($tot->stock, $tot->id);
        }
    }

    private function setAmount($stock, $id)
    {

    }
}
